import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';

import prettierPlugin from 'eslint-plugin-prettier';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    plugins: {
      prettier: prettierPlugin,
    },
    rules: {
      'prettier/prettier': 'error',
    },
  },
  {
    // Legacy static frontend — the tool pages under frontend/ that predate
    // the Next.js app. Kept deliberately permissive: there are ~750 console
    // calls and legacy patterns in these files, so don't try to fix them all
    // here. This block only flags the two things that are never accidental:
    // leftover `debugger` statements and undefined-variable usage.
    files: ['frontend/**/*.js', 'frontend/**/*.mjs', 'frontend/**/*.cjs'],
    ignores: ['**/*.patch.js', '**/*.min.js'],
    languageOptions: {
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
        consoleInfo: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        MutationObserver: 'readonly',
        URLSearchParams: 'readonly',
        FormData: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        Image: 'readonly',
        Audio: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        AbortController: 'readonly',
        DOMParser: 'readonly',
        XMLHttpRequest: 'readonly',
        matchMedia: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        KeyboardEvent: 'readonly',
        MouseEvent: 'readonly',
        TouchEvent: 'readonly',
        PointerEvent: 'readonly',
        confirm: 'readonly',
        alert: 'readonly',
        prompt: 'readonly',
        location: 'readonly',
        history: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLMediaElement: 'readonly',
        CSS: 'readonly',
        MediaRecorder: 'readonly',
        WebSocket: 'readonly',
        BroadcastChannel: 'readonly',
        Notification: 'readonly',
        screen: 'readonly',
        visualViewport: 'readonly',
        webkitAudioContext: 'writable',
        AudioContext: 'readonly',
        ga: 'readonly',
        caches: 'readonly',
        self: 'readonly',
        // Cross-script / cross-page globals shared under frontend/:
        AbortSignal: 'readonly',
        ActiveXObject: 'readonly',
        adsbygoogle: 'writable',
        ApexCharts: 'readonly',
        ArcadeManager: 'readonly',
        AuthSystem: 'readonly',
        Bun: 'readonly',
        ChatSystem: 'readonly',
        CompliantAdSystem: 'readonly',
        debounce: 'readonly',
        decodeBase64ToArray: 'readonly',
        Deno: 'readonly',
        DeveloperMenu: 'readonly',
        devicePixelRatio: 'readonly',
        domAdmin: 'readonly',
        DOMRect: 'readonly',
        dprint: 'readonly',
        dump: 'readonly',
        Element: 'readonly',
        event: 'readonly',
        GameEngine: 'readonly',
        getComputedStyle: 'readonly',
        global: 'readonly',
        hideEditModal: 'readonly',
        HTMLScriptElement: 'readonly',
        IDBKeyRange: 'readonly',
        importScripts: 'readonly',
        indexedDB: 'readonly',
        initializePlayersListManager: 'readonly',
        io: 'readonly',
        isNumber: 'readonly',
        isPointerType: 'readonly',
        joinActiveQuiz: 'readonly',
        lanIP: 'readonly',
        listenToArticles: 'readonly',
        loadArticles: 'readonly',
        loadCommunityTab: 'readonly',
        loadEmployees: 'readonly',
        loadShifts: 'readonly',
        loadTimeOffRequests: 'readonly',
        lofi: 'readonly',
        ManageShared: 'readonly',
        MarketSystem: 'readonly',
        meSpeakCore: 'readonly',
        MessageChannel: 'readonly',
        module: 'readonly',
        navigation: 'readonly',
        NewResourceManager: 'readonly',
        Node: 'readonly',
        openDosGame: 'readonly',
        openUnifiedCacheDB: 'readonly',
        Option: 'readonly',
        performance: 'readonly',
        pointingLevels: 'readonly',
        postMessage: 'readonly',
        queueMicrotask: 'readonly',
        QuizLogic: 'readonly',
        QuizPlayerHandler: 'readonly',
        QuizQuestionHandler: 'readonly',
        QuizSocketHandler: 'readonly',
        QuizTimerHandler: 'readonly',
        __REACT_DEVTOOLS_GLOBAL_HOOK__: 'readonly',
        ReadableStream: 'readonly',
        readline: 'readonly',
        RebirthRewards: 'readonly',
        RebirthThemes: 'readonly',
        renderHud: 'readonly',
        renderUpgradeList: 'readonly',
        reportError: 'readonly',
        requestIdleCallback: 'readonly',
        require: 'readonly',
        ResourceManager: 'readonly',
        RTCPeerConnection: 'readonly',
        SaveManager: 'readonly',
        setImmediate: 'readonly',
        showArticleDetails: 'readonly',
        showConfirmDialog: 'readonly',
        showLoading: 'readonly',
        showNotification: 'readonly',
        showRejectModal: 'readonly',
        showWelcomeBackModal: 'readonly',
        SpeechSynthesisUtterance: 'readonly',
        startWebDownload: 'readonly',
        SupportAuthSystem: 'readonly',
        SupportChatSystem: 'readonly',
        switchTab: 'readonly',
        TextDecoder: 'readonly',
        TextEncoder: 'readonly',
        TURBOPACK_NEXT_CHUNK_URLS: 'readonly',
        Types: 'readonly',
        UIManager: 'readonly',
        UIThemeManager: 'readonly',
        UpgradeSystem: 'readonly',
        WebAssembly: 'readonly',
        Worker: 'readonly',
        WorkerGlobalScope: 'readonly',
      },
      ecmaVersion: 'latest',
      sourceType: 'script',
    },
    rules: {
      'no-debugger': 'error',
      'no-undef': 'error',
      // Everything else is intentionally off for this legacy tree.
      'no-console': 'off',
      'no-unused-vars': 'off',
      'prettier/prettier': 'off',
      'no-empty': 'off',
      'no-redeclare': 'off',
      'no-constant-condition': 'off',
      'no-unreachable': 'off',
      'no-func-assign': 'off',
      'no-dupe-keys': 'off',
      'no-dupe-args': 'off',
      'no-inner-declarations': 'off',
      'no-prototype-builtins': 'off',
      'no-control-regex': 'off',
      'no-useless-escape': 'off',
      'no-cond-assign': 'off',
      'no-case-declarations': 'off',
      'no-undef-init': 'off',
      'no-self-assign': 'off',
      // TypeScript-flavored rules from the base config don't apply to
      // this vanilla-JS tree:
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      '@typescript-eslint/no-this-alias': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      'react-hooks/rules-of-hooks': 'off',
      'react-hooks/exhaustive-deps': 'off',
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Build artifacts and partial patch files under the legacy frontend:
    'frontend/**/*.min.js',
    'frontend/**/*.patch.js',
    'frontend/**/vendor/**',
  ]),
]);

export default eslintConfig;
